---
dir: "unfetter-store/unfetter-threat-ingest"
path: "{{ prepath + dir}}"
container_name: unfetter-threat-ingest
image_name: "{{registry}}{{ container_name }}:{{docker_tag}}"

base_list: "certs:/etc/pki/tls/certs:ro"
dev_volume_list: ",{{ path }}/config:/usr/src/unfetter-threat-ingest/config,{{ path }}/src:/usr/src/unfetter-threat-ingest/src"

volume_list: "{{ base_list }}{{ dev_volume_list if run_mode == 'dev' else '' }}"
