version: '2'
services:
  unfetter-discover-gateway:
    image: nginx:1.11
    container_name: unfetter-discover-gateway
    ports:
     - "443:443"
     - "80:80"
    depends_on:
     - unfetter-discover-openssl
    links:
     - unfetter-ui
     - cti-stix-store
     - unfetter-discover-api-explorer
     - unfetter-discover-api
     #- unfetter-socket-server
    volumes:
     - ./config/nginx/conf.d.demo:/etc/nginx/conf.d
     - ./certs/:/etc/pki/tls/certs

  unfetter-ui:
    build: ../unfetter-ui
    image: unfetter-ui
    container_name: unfetter-ui
    ports:
     - "50000:50000"
    depends_on:
     - unfetter-discover-openssl
    volumes:
     - ./certs/:/etc/pki/tls/certs
    entrypoint:
     - ember
     - server
     - -live-reload-port
     - "50000"
     - -ssl
     - -ssl-key
     - /etc/pki/tls/certs/server.key
     - -ssl-cert
     - /etc/pki/tls/certs/server.crt

  unfetter-discover-openssl:
    image: svagi/openssl:latest
    container_name: unfetter-discover-openssl
    entrypoint:
     - openssl
     - req
     - -subj
     - /CN=localhost/DC=localhost/DC=localdomain
     - -new
     - -newkey
     - rsa:2048
     - -days
     - "365"
     - -nodes
     - -x509
     - -keyout
     - /tmp/certs/server.key
     - -out
     - /tmp/certs/server.crt
    volumes:
     - ./certs/:/tmp/certs

  unfetter-discover-processor:
    image: unfetter/unfetter-discover-processor 
    container_name: unfetter-discover-processor
    volumes:
     - ./config/examples:/tmp/examples
    entrypoint:
     - node
     - processor-direct.js
     - -p
     - "3000"
     - -h
     - cti-stix-store
     - -r
     - repository
     - -x
     - "27017"
     - -c
     - stix
     - -j
     - /tmp/examples/mitre-attack-cis/stix.json
    depends_on:
     - cti-stix-store
     - cti-stix-store-repository
    links:
     - cti-stix-store-repository:repository
    environment:
    - INCLUDE_MITRE_GITHUB_DATA=false

  cti-stix-store:
    image: unfetter/cti-stix-store 
    container_name: cti-stix-store
    depends_on:
     - cti-stix-store-repository
    links:
     - cti-stix-store-repository:repository
    volumes:
     - ./config/schema/examples/schemas:/tmp/schemas
    environment:
     - SCHEMA_LOCATION=/tmp/schemas
    command: /bin/ash wait-for-repository.sh

  cti-stix-store-repository:
    image: mongo:3.4.1
    container_name: cti-stix-store-repository
    ports:
    - "27018:27017"
    volumes:
    - /data/db:/data/db

  cti-stix-ui:
    image: unfetter/cti-stix-ui 
    container_name: cti-stix-ui
    ports:
     - "40000:40000"
    depends_on:
    - unfetter-discover-openssl
    volumes:
     - ./certs/:/etc/pki/tls/certs
    entrypoint:
     - ember
     - server
     - -live-reload-port
     - "40000"
     - -ssl
     - -ssl-key
     - /etc/pki/tls/certs/server.key
     - -ssl-cert
     - /etc/pki/tls/certs/server.crt

  unfetter-discover-api-explorer:
    image: unfetter/unfetter-discover-api
    container_name: unfetter-discover-api-explorer
    depends_on:
    - unfetter-discover-openssl
    - cti-stix-store-repository
    expose:
    - "3000"
    ports:
    - "49260:3000"
    links:
     - cti-stix-store-repository:repository
    volumes:
    - ./certs/:/etc/pki/tls/certs
    environment:
    - STIX_API_PROTOCOL=http
    - STIX_API_HOST=cti-stix-store
    - STIX_API_PORT=3000
    - STIX_API_PATH=cti-stix-store-api
    - MONGO_REPOSITORY=repository
    - MONGO_PORT=27017
    - MONGO_DBNAME=stix
    - ENV=prod
    entrypoint:
    - npm
    - run
    - swagger-editor

  unfetter-discover-api:
    image: unfetter/unfetter-discover-api
    container_name: unfetter-discover-api
    depends_on:
    - unfetter-discover-openssl
    - cti-stix-store-repository
    links:
     - cti-stix-store-repository:repository
    ports:
    - "49360:3000"
    volumes:
    - ./certs/:/etc/pki/tls/certs
    environment:
    - STIX_API_PROTOCOL=http
    - STIX_API_HOST=cti-stix-store
    - STIX_API_PORT=3000
    - STIX_API_PATH=cti-stix-store-api
    - MONGO_REPOSITORY=repository
    - MONGO_PORT=27017
    - MONGO_DBNAME=stix
    - ENV=dev
    entrypoint:
    - npm
    - start
