version: '3.3'
services:
  unfetter-discover-gateway:
    build: ./gateway
    image: unfetter-discover-gateway
    container_name: unfetter-discover-gateway
    ports:
     - "443:443"
     - "80:80"
    depends_on:
     - unfetter-discover-openssl
    links:
     - unfetter-api-explorer
     - unfetter-discover-api
    volumes:
     - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
     - ./config/nginx/conf.d.extra/:/etc/nginx/conf.d.extra
     - ./certs/:/etc/pki/tls/certs

  unfetter-discover-processor:
    build: ../unfetter-store/unfetter-discover-processor
    container_name: unfetter-discover-processor
    image: unfetter-discover-processor

  unfetter-ctf-ingest:
    build: ../unfetter-store/unfetter-ctf-ingest
    container_name: unfetter-ctf-ingest
    image: unfetter-ctf-ingest
    volumes:
     - ../unfetter-store/unfetter-ctf-ingest/test-data:/tmp/test-data
     - ../unfetter-store/unfetter-ctf-ingest/src:/usr/share/unfetter-ctf-ingest/src

  unfetter-api-explorer:
    build: 
      context: ../unfetter-store
      dockerfile: unfetter-api-explorer/parent-context.Dockerfile
    container_name: unfetter-api-explorer
    image: unfetter-api-explorer
    volumes:
     - ../unfetter-store/unfetter-api-explorer/src:/usr/share/unfetter-api-explorer/src
     - ../unfetter-store/unfetter-discover-api/multifile-remote.yaml:/usr/share/unfetter-discover-api/multifile-remote.yaml
     - ../unfetter-store/unfetter-discover-api/api/swagger:/usr/share/unfetter-discover-api/api/swagger
    environment:
     - PUBLIC_PATH=/explorer/
    entrypoint:
     - npm
     - start

  unfetter-discover-api:
    build: ../unfetter-store/unfetter-discover-api
    container_name: unfetter-discover-api
    image: unfetter-discover-api
    depends_on:
    - unfetter-discover-openssl
    - cti-stix-store-repository
    volumes:
    - ./certs/:/etc/pki/tls/certs
    - ../unfetter-store/unfetter-discover-api/test:/usr/share/unfetter-discover-api/test
    - ../unfetter-store/unfetter-discover-api/api:/usr/share/unfetter-discover-api/api
    - ../unfetter-store/unfetter-discover-api/app.js:/usr/share/unfetter-discover-api/app.js
    - ../unfetter-store/unfetter-discover-api/config/private:/usr/share/unfetter-discover-api/config/private
    entrypoint:
    - npm
    - run
    - startdeploy

  unfetter-pattern-handler:
    build: ../stix2pattern
    container_name: unfetter-pattern-handler
    image: unfetter-pattern-handler
    volumes:
      - ../stix2pattern/app.py:/opt/stix/app.py
      - ../stix2pattern/test.py:/opt/stix/test.py

  unfetter-socket-server:
    build: ../unfetter-store/unfetter-socket-server
    container_name: unfetter-socket-server
    image: unfetter-socket-server
    volumes:
      - ../unfetter-store/unfetter-socket-server/src:/usr/share/unfetter-socket-server/src
      - ./certs/:/etc/pki/tls/certs
      - ../unfetter-store/unfetter-socket-server/config/private:/usr/share/unfetter-socket-server/config/private
    environment:
      - MONGO_REPOSITORY=repository
      - MONGO_PORT=27017
      - MONGO_DBNAME=stix
    entrypoint:
     - npm
     - start
    depends_on:
     - cti-stix-store-repository
    links:
     - cti-stix-store-repository:repository
