version: '3.3'
services:
  unfetter-elk:
    image: sebp/elk:630
    container_name: unfetter-elk
    ports:
    - "5601:5601"
    - "9200:9200"
    - "5044:5044"

  unfetter-filebeat:
    image: prima/filebeat:6
    container_name: unfetter-filebeat
    links:
     - unfetter-elk
    depends_on:
     - unfetter-elk
     - unfetter-discover-gateway
    volumes:
     - ./config/elk/filebeat.yml:/filebeat.yml
     - ./config/elk/logstash-beats.crt:/etc/pki/tls/certs/logstash-beats.crt
     - log-vol:/var/log

  unfetter-discover-gateway:
    image: nginx:1.13.5-alpine
    container_name: unfetter-discover-gateway
    depends_on:
     - unfetter-discover-openssl
    links:
     - unfetter-elk
    volumes:
     - ./config/nginx/logging.conf:/etc/nginx/conf.d.runmode/logging.conf
     - ./config/scripts/gateway-deploy-entry.sh:/gateway-deploy-entry.sh
     - log-vol:/var/log
    entrypoint:
     - /gateway-deploy-entry.sh

volumes:
  log-vol:
