
####################################################################################
#  This playbook builds a new api-config
#  playbook.
#  Specific target hosts can be built using the following:
#  ansible-playbook -i dev discover.yml
#
#
####################################################################################


- name: check-private
  listen: load private-vol
  stat:
    path: '{{ private_vol }}/private-config.json'
  register: private_vol_stat
  changed_when: True  
  notify:
    - Private Config Tested