
####################################################################################
#  This playbook builds a new api-config
#  playbook.
#  Specific target hosts can be built using the following:
#  ansible-playbook -i dev discover.yml
#
#
####################################################################################


- debug: msg="Forcing Reconfigure of the Private Config"
  changed_when: True  

- name: include tasks to build the private config file
  include_tasks: handlers/build-private-config.yml
   

- name: Create Directory2
  file: path={{ private_vol }} state=directory



# Create the new private-config.json.  Then, restart to first handler to copy the private-config
- name: Private Config Tested Config2
  #when: "not (private_vol_stat.stat.exists)"
  template:
    src: private-config.j2
    dest: "{{ private_vol }}/private-config.json"

# The private file exists.  So, copy it into the volume
- name: Restore Private From Backup1
  command: "{{ item }}"
  with_items:
    - docker run -v private-config:/config/private --name helper busybox true
    - docker cp {{ private_vol }}/private-config.json helper:/config/private
    - docker rm helper
