# If the private-config is not there, then ask the user for the input information

# Ask if GitHub authentication
- pause:
    prompt: "\tPlease enter the GitHub application client ID: "
  listen: Private Config Tested          
  #when: '"github" in auth_services and not (private_vol_stat.stat.exists)'
  when: '"github" in auth_services'
  register: github_clientID_register

- pause:
    prompt: "\n\tPlease enter the GitHub application client secret: '"
  listen: Private Config Tested
  #when: '"github" in auth_services and not (private_vol_stat.stat.exists)'
  when: '"github" in auth_services'
  register: github_clientSecret_register

# Git Gitlab info
- pause:
    prompt: "\n\tPlease enter the GitLb application client ID:'"
  listen: Private Config Tested    
  #when: '"gitlab" in auth_services and not (private_vol_stat.stat.exists)'
  when: '"gitlab" in auth_services'
  register: gitlab_clientID_register

- pause:
    prompt: "\n\tPlease enter the GitLb application client secret:"
  listen: Private Config Tested    
  #when: '"gitlab" in auth_services and not (private_vol_stat.stat.exists)'
  when: '"gitlab" in auth_services'
  register: gitlab_clientSecret_register
  
# Session and JWT standard secret information      
- pause:
    prompt: "Enter JWT secret "
  #when: "not (private_vol_stat.stat.exists)"    
  listen: Private Config Tested    
  register: secret_jwt_register

- pause:
    prompt: "Enter session secret "
  #when: "not (private_vol_stat.stat.exists)"      
  listen: Private Config Tested    
  register: secret_session_register
