---
- hosts: localhost
  vars:
    tag: "0.3.6"

    prepath: "../../"
    

    # For building from a repository 
    build_action: "pull" 
    registry: "unfetter/"
    run_mode: "production"
    # For running in demo mode
    use_unfetter_ui: false
    run_action: false
    use_uac: false
    use_taxii: false



    #prepath: "../../"
    #build_action: "local" 
    #build_action: ""
    #run_action: ""
    #registry: ""

    

  tasks:
  - include_role:
        name: common
  - include_role:
        name: openssl
  - include_role:
        name: pattern-handler
  - include_role:
        name: api
  - include_role:
        name: explorer
  - include_role:
        name: processor
  - include_role:
        name: socket-server
  - include_role:
        name: ui
  - include_role:
        name: ingest        
  - include_role:
        name: gateway
    vars:
        image_name: "nginx:1.13.5-alpine"
