---
- hosts: localhost
  vars:
    tag: "0.3.6"
    prepath: "../../"
    # For building from a repository 
    build_action: "pull" 
    registry: "unfetter/"
    run_mode: "production"
    # For running in demo mode
    use_unfetter_ui: false
    run_action: true
    use_uac: false
    use_taxii: false

  tasks:
  - import_tasks: discover-tasks.yml
