---
- hosts: localhost
  vars:
    tag: "0.3.6"
    prepath: "../../"    

    # For building from a repository 
    build_action: "pull" 
    registry: "unfetter/"
    run_mode: "production"

    # For running in demo mode
    use_unfetter_ui: false
    run_action: false
    use_uac: false
    use_taxii: false
    use_taxii_tls: false
    #prepath: "../../"
    #build_action: "local" 
    #build_action: ""
    #run_action: ""
    #registry: ""    

  tasks:
  - import_tasks: discover-tasks.yml
