---
- hosts: localhost
  vars:
    tag: "0.3.6"
    prepath: "../../"

    # For building from local source
    build_action: "local" 
    registry: ""
    run_mode: "dev"
    
    # for running in UAC mode
    run_action: true
    use_unfetter_ui: true
    use_uac: true
    use_taxii: true        
    use_taxii_tls: false        

  tasks:
  - import_tasks: discover-tasks.yml
