---
####################################################################################
#  This playbook will upgrade from 0.3.7 to 0.3.8  
#
####################################################################################

- name: Upgrades Unfetter to support version 0.3.8
  hosts: dev
  tasks:
    - include_role:
          name: common
          tasks_from: migrate-0.3.9.yml