---
####################################################################################
#  This playbook only builds the docker images locally
#
####################################################################################


- name: Pushes local images to a registry
  hosts: build
#  become: true
  vars:
    registry: "unfetter/"
#     next_tag: "0.3.9"
#     beta_version: ".beta.3"
    image_list:
         - "unfetter-api-explorer"
         - "unfetter-discover-processor"
         - "unfetter-discover-api"
         - "unfetter-ui"
         - "unfetter-ctf-ingest"
         - "unfetter-pattern-handler"

    gateway_config:
         - "uac"
         - "legacy.uac"
         - "legacy.demo"
         - "demo"
  tasks:

 # - debug:
    - name: Tagging with Latest
      command: "docker tag {{ item }}:{{ docker_tag }} {{ registry }}{{ item }}:latest"
      with_items: "{{ image_list }}"
    - name: Tagging gateway with latest
      command: "docker tag unfetter-discover-gateway:{{ docker_tag }}.demo {{ registry }}unfetter-discover-gateway:latest"

    - name: Tagging with {{ next_tag }}
      command: "docker tag {{ item }}:{{ docker_tag }} {{ registry }}{{ item }}:{{ next_tag }}"
      with_items: "{{ image_list }}"       

    - name: Tagging Gateway with {{ next_tag }}
      command: "docker tag unfetter-discover-gateway:{{ docker_tag }}.{{ item }} {{ registry }}unfetter-discover-gateway:{{ next_tag }}.{{ item }}"
      with_items: "{{ gateway_config }}"


    - name: Pushing to {{ registry }}
      command: "docker push {{ registry }}{{ item }}:{{ next_tag }}"
      with_items: "{{ image_list }}"        
    - name: Pushin Gateway with {{ registry }}
      command: "docker push {{ registry }}unfetter-discover-gateway:{{ next_tag }}.{{ item }}"
      with_items: "{{ gateway_config }}"

 
